services:
  - type: web
    name: placarzin
    runtime: ruby
    plan: free
    rootDir: app
    staticPublishPath: ./public
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec rails server'
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2