services:
  - type: web
    name: placarzin
    env: static
    branch: main
    rootDir: app
    buildCommand: "./../bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    staticPublishPath: ./views/pages
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
